- hosts: ix
  gather_facts: no

  tasks:
    - name: collect
      ios_command:
        commands:
          - configure
          - terminal length 0
          - show clock
          - show ip bgp
      register: result

    - name: show clock
      debug:
        msg: "{{ result.stdout_lines[2] }}"

    - name: show ip bgp
      debug:
        msg: "{{ result.stdout_lines[3] }}"

